spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: ${pet.datasource.driver-class-name}
    url: jdbc:mysql://${pet.datasource.host}:${pet.datasource.port}/${pet.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${pet.datasource.username}
    password: ${pet.datasource.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.pethub.pojo.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      pethub:
        mapper: debug
        service: info
        controller: info

pethub:
  jwt:
    secret-key: pethub-admin-secret-key-please-change-32
    ttl: 72000000
    token-name: Authorization
    algorithm: HS256
